trigger:
- master

jobs:
- job: Regular
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1

- job: UseVenv
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1
      arguments: -UseVenv

- job: Ramdisk
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  # Have to split this into two tasks so that powershell can rehash
  # $PATH, or... something like that.
  - task: PowerShell@2
    inputs:
      filePath: imdisk-install.ps1
  - task: PowerShell@2
    inputs:
      filePath: imdisk-venv.ps1

  - job: MyPython
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: my-python.ps1
